
language: generic

sudo: required

services:
 - docker

 before_install:
 - docker build -t harimadala/docker-react -f Dockerfile.dev .

script:
 - docker run harimadala/docker-react npm run test -- --coverage